language: node_js
node_js:
  - "10"
os: linux
dist: trusty
services:
  - mongodb
env:
  - NODE_ENV=ci
cache:
  directories:
    - node_modules
install:
  - npm install
script:
  - nohup npm run startTravis &
  - sleep 30
  - npm run test