language: node_js
node_js:
  - "10"
dist: trusty
services:
  - mongodb
env:
  - NODE_ENV=ci
cache:
  directories:
    - node_modules
install:
  - npm install
  - npm run build
script:
  - nohup npm run start &
  - sleep 6
  - npm run test